TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 0.3
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 0.08
  acc_lim_x: 0.08
  acc_lim_y: 0.08

  holonomic_robot: false

NavfnROS:
   allow_unknown: false