DWAPlannerROS:
  acc_lim_theta: 4
  acc_lim_x: 2
  acc_lim_y: 0.1

  max_trans_vel: 0.3
  min_trans_vel: 0.1
  max_vel_x: 0.3
  min_vel_x: -0.2
  max_vel_y: 0
  min_vel_y: 0
  max_rot_vel: 0.5
  min_rot_vel: 0.1

  vx_samples: 5
  vy_samples: 1